// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Todos.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class TodoItem
    {
        /// <summary>
        /// Initializes a new instance of the TodoItem class.
        /// </summary>
        public TodoItem()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the TodoItem class.
        /// </summary>
        public TodoItem(double id, string text)
        {
            Id = id;
            Text = text;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public double Id { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "text")]
        public string Text { get; private set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
