/* 
 * Todo MVC backend style API
 *
 * This is a simple API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: you@your-company.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Todos.Apis;
using Todos.Models;
using Todos.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Todos.Test
{
    /// <summary>
    ///  Class for testing UpdateTodoItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UpdateTodoItemTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UpdateTodoItem
        //private UpdateTodoItem instance;

        public UpdateTodoItemTests()
        {
            // TODO uncomment below to create an instance of UpdateTodoItem
            //instance = new UpdateTodoItem();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UpdateTodoItem
        /// </summary>
        [Fact]
        public void UpdateTodoItemInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" UpdateTodoItem
            //Assert.IsInstanceOfType<UpdateTodoItem> (instance, "variable 'instance' is a UpdateTodoItem");
        }


        /// <summary>
        /// Test the property 'Text'
        /// </summary>
        [Fact]
        public void TextTest()
        {
            // TODO unit test for the property 'Text'
        }

    }

}
